<<<<<<< HEAD
spring.application.name=api-demo


# CONFIGURACIÓN PARA MYSQL EN DOCKER


# Conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3307/mi_app_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Guatemala
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=app_user
spring.datasource.password=app_pass123


# JPA / Hibernate

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# CONFIGURACIÓN DE SWAGGER

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true



# JWT CONFIGURATION

jwt.public-key-path=keys/public_key.pem
jwt.issuer=seguridad-api


# SEGURIDAD API URL
=======
spring.application.name=api-demo


# CONFIGURACIÓN PARA MYSQL EN DOCKER


# Conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3307/mi_app_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Guatemala
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=app_user
spring.datasource.password=app_pass123


# JPA / Hibernate

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# CONFIGURACIÓN DE SWAGGER

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true



# JWT CONFIGURATION

jwt.public-key-path=keys/public_key.pem
jwt.issuer=seguridad-api


# SEGURIDAD API URL
>>>>>>> ffcf5a27d8dc35521b8fa58bbb4e95f6aef4e943
seguridad.api.url=http://localhost:8081/auth/validate